In [1]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("preprocessed.csv") 
print(data.shape)  
data.head()

(1819, 94)


url_length  special_character_count  dns_response_time  handshake_time  \
0          27                        2           1.866579      809.915781   
1          12                        2         654.555559     3379.443407   
2          92                       12          57.567120     2735.617161   
3          24                        3           1.390219     1009.941101   
4          29                        2           1.077890     6096.054077   

    data_time  data_length  scripts_count  iframe_count  external_link_count  \
0  185.235262     301912.0            8.0           6.0                 73.0   
1  799.807549     162844.0           33.0           0.0                 18.0   
2   29.102325     129957.0           55.0           2.0                 58.0   
3    0.138521       3453.0            1.0           0.0                  1.0   
4  350.750208     204520.0           85.0           4.0                 41.0   

   total_strings_count  ...  server_name_nginx/1.14.1  \
0              26397.0  ...                         0   
1               9289.0  ...                         0   
2              22093.0  ...                         0   
3                  8.0  ...                         1   
4               8248.0  ...                         0   

   server_name_nginx/1.14.2  server_name_nginx/1.15.6  \
0                         0                         0   
1                         0                         0   
2                         0                         0   
3                         0                         0   
4                         0                         0   

   server_name_nginx/1.4.6 (Ubuntu)  server_name_openresty  \
0                                 0                      0   
1                                 0                      0   
2                                 0                      0   
3                                 0                      0   
4                                 0                      0   

   server_name_server_name_nan  server_name_server_name_single  \
0                            0                               0   
1                            0                               0   
2                            0                               0   
3                            0                               0   
4                            0                               0   

   server_name_tsa_k  label                                           url_name  
0                  1   good                        twitter.com/aQuariusrecOrds  
1                  0   good                                       tong464.org/  
2                  0   good  legacy.com/obituaries/orlandosentinel/obituary...  
3                  0   good                           natcath.org/ncr_onli.htm  
4                  0   good                      wn.com/San_Diego_State_Aztecs  

[5 rows x 94 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder

data.iloc[:,92] = LabelEncoder().fit_transform(data.iloc[:,92])
data = data.interpolate(method ='linear', limit_direction ='forward') 
X = data.drop(data.columns[[92,93]],axis=1)
y = data.iloc[:,92]

In [4]:
from sklearn import preprocessing
x = X.values
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
X = pd.DataFrame(x_scaled)

In [5]:
X.columns[X.isna().any()].tolist()

[]

In [6]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20) 

In [7]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train) 

y_pred = svclassifier.predict(X_test)  

In [8]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

[[  1  45]
 [  0 318]]
              precision    recall  f1-score   support

           0       1.00      0.02      0.04        46
           1       0.88      1.00      0.93       318

   micro avg       0.88      0.88      0.88       364
   macro avg       0.94      0.51      0.49       364
weighted avg       0.89      0.88      0.82       364



In [12]:
print(np.unique(y_test,return_counts=True))
print(np.unique(y_pred,return_counts=True))

(array([0, 1]), array([ 46, 318]))
(array([0, 1]), array([  1, 363]))
